"""Seed the database with sample property listings."""

import os
from app.database import engine, SessionLocal, Base
from app.models.property import Property, PropertyType, ListingStatus

PROPERTIES = [
    {
        "title": "Modern Downtown Loft",
        "description": "Stunning open-concept loft in the heart of downtown with floor-to-ceiling windows, exposed brick walls, and polished concrete floors. Features a chef's kitchen with quartz countertops and stainless steel appliances. Walking distance to restaurants, shops, and public transit.",
        "price": 425000,
        "address": "742 Evergreen Terrace",
        "city": "Austin",
        "state": "TX",
        "zip_code": "78701",
        "bedrooms": 2,
        "bathrooms": 2.0,
        "square_footage": 1200,
        "property_type": PropertyType.CONDO,
        "listing_status": ListingStatus.ACTIVE,
        "photos": [
            "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800",
            "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800",
        ],
        "latitude": 30.2672,
        "longitude": -97.7431,
    },
    {
        "title": "Spacious Family Home",
        "description": "Beautiful 4-bedroom family home on a quiet cul-de-sac. Features a large backyard with mature trees, updated kitchen with granite countertops, hardwood floors throughout, and a finished basement perfect for a home office or playroom.",
        "price": 575000,
        "address": "1234 Oak Lane",
        "city": "Denver",
        "state": "CO",
        "zip_code": "80202",
        "bedrooms": 4,
        "bathrooms": 3.0,
        "square_footage": 2800,
        "property_type": PropertyType.HOUSE,
        "listing_status": ListingStatus.ACTIVE,
        "photos": [
            "https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=800",
            "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800",
        ],
        "latitude": 39.7392,
        "longitude": -104.9903,
    },
    {
        "title": "Charming Victorian Townhouse",
        "description": "Meticulously restored Victorian townhouse blending period charm with modern amenities. Crown molding, original hardwood floors, and a private garden patio. Updated plumbing, electrical, and HVAC systems. Two-car garage included.",
        "price": 689000,
        "address": "56 Heritage Row",
        "city": "Portland",
        "state": "OR",
        "zip_code": "97201",
        "bedrooms": 3,
        "bathrooms": 2.5,
        "square_footage": 2100,
        "property_type": PropertyType.TOWNHOUSE,
        "listing_status": ListingStatus.ACTIVE,
        "photos": [
            "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800",
            "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=800",
        ],
        "latitude": 45.5152,
        "longitude": -122.6784,
    },
    {
        "title": "Luxury Waterfront Condo",
        "description": "Breathtaking waterfront condo with panoramic ocean views from every room. Features an open floor plan, gourmet kitchen, spa-like master bath, and a wrap-around balcony. Building amenities include pool, gym, concierge, and private beach access.",
        "price": 1250000,
        "address": "88 Marina Blvd, Unit 1201",
        "city": "Miami",
        "state": "FL",
        "zip_code": "33101",
        "bedrooms": 3,
        "bathrooms": 3.0,
        "square_footage": 2400,
        "property_type": PropertyType.CONDO,
        "listing_status": ListingStatus.ACTIVE,
        "photos": [
            "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=800",
            "https://images.unsplash.com/photo-1600047509807-ba8f99d2cdde?w=800",
        ],
        "latitude": 25.7617,
        "longitude": -80.1918,
    },
    {
        "title": "Cozy Starter Home",
        "description": "Adorable starter home perfect for first-time buyers. Recently renovated with new roof, windows, and modern kitchen. Fenced backyard, one-car garage, and a charming front porch. Located in a friendly neighborhood near parks and schools.",
        "price": 285000,
        "address": "321 Maple Street",
        "city": "Nashville",
        "state": "TN",
        "zip_code": "37201",
        "bedrooms": 2,
        "bathrooms": 1.0,
        "square_footage": 1050,
        "property_type": PropertyType.HOUSE,
        "listing_status": ListingStatus.ACTIVE,
        "photos": [
            "https://images.unsplash.com/photo-1600573472591-ee6b68d14c68?w=800",
            "https://images.unsplash.com/photo-1599427303058-f04cbcf4756f?w=800",
        ],
        "latitude": 36.1627,
        "longitude": -86.7816,
    },
    {
        "title": "Mountain View Estate",
        "description": "Spectacular mountain estate on 5 acres with sweeping views of the Rockies. Custom-built with timber frame construction, stone fireplace, chef's kitchen, wine cellar, and heated three-car garage. Ideal for those seeking privacy and natural beauty.",
        "price": 1850000,
        "address": "9100 Summit Ridge",
        "city": "Boulder",
        "state": "CO",
        "zip_code": "80302",
        "bedrooms": 5,
        "bathrooms": 4.5,
        "square_footage": 4500,
        "property_type": PropertyType.HOUSE,
        "listing_status": ListingStatus.ACTIVE,
        "photos": [
            "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800",
            "https://images.unsplash.com/photo-1605276374104-dee2a0ed3cd6?w=800",
        ],
        "latitude": 40.0150,
        "longitude": -105.2705,
    },
    {
        "title": "Urban Studio Apartment",
        "description": "Efficient and stylish studio in a modern high-rise. Features floor-to-ceiling windows with city views, in-unit washer/dryer, and a sleek kitchenette. Building includes rooftop terrace, fitness center, and 24-hour security. Perfect for young professionals.",
        "price": 195000,
        "address": "500 City Center Dr, Unit 814",
        "city": "Chicago",
        "state": "IL",
        "zip_code": "60601",
        "bedrooms": 1,
        "bathrooms": 1.0,
        "square_footage": 550,
        "property_type": PropertyType.APARTMENT,
        "listing_status": ListingStatus.ACTIVE,
        "photos": [
            "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800",
            "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800",
        ],
        "latitude": 41.8781,
        "longitude": -87.6298,
    },
    {
        "title": "Suburban Ranch with Pool",
        "description": "Single-story ranch home with resort-style backyard featuring a heated pool, covered patio, and outdoor kitchen. Open layout with vaulted ceilings, updated master suite, and a three-car garage. Great school district.",
        "price": 495000,
        "address": "2250 Sunset Drive",
        "city": "Phoenix",
        "state": "AZ",
        "zip_code": "85001",
        "bedrooms": 4,
        "bathrooms": 2.5,
        "square_footage": 2200,
        "property_type": PropertyType.HOUSE,
        "listing_status": ListingStatus.PENDING,
        "photos": [
            "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800",
            "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=800",
        ],
        "latitude": 33.4484,
        "longitude": -112.0740,
    },
    {
        "title": "Historic Brownstone",
        "description": "Elegant three-story brownstone in a historic neighborhood. Original architectural details include carved mantels, pocket doors, and ornate plasterwork. Updated kitchen and bathrooms, central air, and a private rooftop deck with skyline views.",
        "price": 975000,
        "address": "14 Beacon Hill Place",
        "city": "Boston",
        "state": "MA",
        "zip_code": "02108",
        "bedrooms": 4,
        "bathrooms": 3.5,
        "square_footage": 3200,
        "property_type": PropertyType.TOWNHOUSE,
        "listing_status": ListingStatus.ACTIVE,
        "photos": [
            "https://images.unsplash.com/photo-1605276374104-dee2a0ed3cd6?w=800",
            "https://images.unsplash.com/photo-1600047509807-ba8f99d2cdde?w=800",
        ],
        "latitude": 42.3601,
        "longitude": -71.0589,
    },
    {
        "title": "Prime Commercial Space",
        "description": "Versatile commercial space in a high-traffic retail corridor. Open floor plan with 16-foot ceilings, large storefront windows, and rear loading dock. Suitable for restaurant, retail, or office use. Ample street parking and nearby public transit.",
        "price": 750000,
        "address": "600 Commerce Street",
        "city": "Seattle",
        "state": "WA",
        "zip_code": "98101",
        "bedrooms": 0,
        "bathrooms": 2.0,
        "square_footage": 3000,
        "property_type": PropertyType.COMMERCIAL,
        "listing_status": ListingStatus.ACTIVE,
        "photos": [
            "https://images.unsplash.com/photo-1497366216548-37526070297c?w=800",
            "https://images.unsplash.com/photo-1497366811353-6870744d04b2?w=800",
        ],
        "latitude": 47.6062,
        "longitude": -122.3321,
    },
    {
        "title": "Lakeside Cottage",
        "description": "Quaint lakeside cottage with private dock and stunning sunset views. Features a stone fireplace, screened-in porch, updated kitchen, and cozy bedrooms. Perfect as a vacation retreat or year-round residence for nature lovers.",
        "price": 340000,
        "address": "78 Lakeshore Road",
        "city": "Asheville",
        "state": "NC",
        "zip_code": "28801",
        "bedrooms": 3,
        "bathrooms": 2.0,
        "square_footage": 1600,
        "property_type": PropertyType.HOUSE,
        "listing_status": ListingStatus.ACTIVE,
        "photos": [
            "https://images.unsplash.com/photo-1600573472591-ee6b68d14c68?w=800",
            "https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=800",
        ],
        "latitude": 35.5951,
        "longitude": -82.5515,
    },
    {
        "title": "New Construction Townhome",
        "description": "Brand-new construction townhome with modern finishes throughout. Open-concept main level, quartz countertops, LVP flooring, and energy-efficient systems. Rooftop terrace with mountain views and attached two-car garage. HOA covers exterior maintenance and landscaping.",
        "price": 465000,
        "address": "101 Innovation Way",
        "city": "Salt Lake City",
        "state": "UT",
        "zip_code": "84101",
        "bedrooms": 3,
        "bathrooms": 2.5,
        "square_footage": 1900,
        "property_type": PropertyType.TOWNHOUSE,
        "listing_status": ListingStatus.ACTIVE,
        "photos": [
            "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=800",
            "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800",
        ],
        "latitude": 40.7608,
        "longitude": -111.8910,
    },
    {
        "title": "Buildable Lot - Ocean Views",
        "description": "Rare 0.75-acre buildable lot with unobstructed ocean views. Utilities stubbed to property line, soil tests complete, and preliminary plans available. Located in an upscale coastal community with beach access. An incredible opportunity to build your dream home.",
        "price": 525000,
        "address": "Parcel 42, Coastal Highway",
        "city": "Santa Cruz",
        "state": "CA",
        "zip_code": "95060",
        "bedrooms": 0,
        "bathrooms": 0,
        "square_footage": 32670,
        "property_type": PropertyType.LAND,
        "listing_status": ListingStatus.ACTIVE,
        "photos": [
            "https://images.unsplash.com/photo-1500382017468-9049fed747ef?w=800",
            "https://images.unsplash.com/photo-1501785888041-af3ef285b470?w=800",
        ],
        "latitude": 36.9741,
        "longitude": -122.0308,
    },
    {
        "title": "Renovated Craftsman Bungalow",
        "description": "Beautifully renovated Craftsman bungalow with original character and modern updates. Features include built-in shelving, a clawfoot tub, updated wiring and plumbing, new HVAC, and a detached workshop. Walkable neighborhood close to local shops and cafes.",
        "price": 395000,
        "address": "456 Artisan Avenue",
        "city": "Savannah",
        "state": "GA",
        "zip_code": "31401",
        "bedrooms": 3,
        "bathrooms": 2.0,
        "square_footage": 1750,
        "property_type": PropertyType.HOUSE,
        "listing_status": ListingStatus.SOLD,
        "photos": [
            "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800",
            "https://images.unsplash.com/photo-1599427303058-f04cbcf4756f?w=800",
        ],
        "latitude": 32.0809,
        "longitude": -81.0912,
    },
    {
        "title": "Penthouse with Skyline Views",
        "description": "Stunning penthouse unit occupying the entire top floor. Features a private elevator entry, floor-to-ceiling glass walls, Italian marble flooring, smart home automation, and a wraparound terrace. Two reserved parking spaces and a private storage unit.",
        "price": 2100000,
        "address": "1 Park Avenue, PH",
        "city": "San Francisco",
        "state": "CA",
        "zip_code": "94102",
        "bedrooms": 3,
        "bathrooms": 3.5,
        "square_footage": 3100,
        "property_type": PropertyType.CONDO,
        "listing_status": ListingStatus.ACTIVE,
        "photos": [
            "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800",
            "https://images.unsplash.com/photo-1600047509807-ba8f99d2cdde?w=800",
        ],
        "latitude": 37.7749,
        "longitude": -122.4194,
    },
]


def seed():
    Base.metadata.create_all(bind=engine)

    # Only seed if RUN_SEED environment variable is set to "true"
    run_seed = os.getenv("RUN_SEED", "false").lower() == "true"

    if not run_seed:
        print("RUN_SEED not set to 'true'. Skipping database seeding.")
        return
    db = SessionLocal()
    try:
        if db.query(Property).count() > 0:
            print("Database already seeded. Skipping.")
            return
        for data in PROPERTIES:
            db.add(Property(**data))
        db.commit()
        print(f"Seeded {len(PROPERTIES)} properties.")
    finally:
        db.close()


if __name__ == "__main__":
    seed()
